package emitter

import ast.*

interface CodeEmitter<E>
{
	fun emitAst(node:KotlinAst):E=
		when(node)
		{
			is KClassHeaderType->emitKClassHeaderType(node)
			is KJumpExpression->emitKJumpExpression(node)
			is KStringLiteral->emitKStringLiteral(node)
			is KSimpleIdentifier->emitKSimpleIdentifier(node)
			is EIsOperator->emitEIsOperator(node)
			is KKotlinFile->emitKKotlinFile(node)
			else->TODO("${node::class.simpleName}")
		}

	fun emitEAnnotationUseSiteTarget(node:EAnnotationUseSiteTarget):E=TODO()
	fun emitEAsOperator(node:EAsOperator):E=TODO()
	fun emitEAssignmentAndOperator(node:EAssignmentAndOperator):E=TODO()
	fun emitEBooleanLiteral(node:EBooleanLiteral):E=TODO()
	fun emitEClassModifier(node:EClassModifier):E=TODO()
	fun emitEComparisonOperator(node:EComparisonOperator):E=TODO()
	fun emitEEqualityOperator(node:EEqualityOperator):E=TODO()
	fun emitEFunctionModifier(node:EFunctionModifier):E=TODO()
	fun emitEInheritanceModifier(node:EInheritanceModifier):E=TODO()
	fun emitEInOperator(node:EInOperator):E=TODO()
	fun emitEIsOperator(node:EIsOperator):E=TODO()
	fun emitEMemberModifier(node:EMemberModifier):E=TODO()
	fun emitEParameterModifier(node:EParameterModifier):E=TODO()
	fun emitERangeOperator(node:ERangeOperator):E=TODO()
	fun emitEVarianceModifier(node:EVarianceModifier):E=TODO()
	fun emitEVisibilityModifier(node:EVisibilityModifier):E=TODO()

	fun emitKAbstractKeyword(node:KAbstractKeyword):E=TODO()
	fun emitKActualKeyword(node:KActualKeyword):E=TODO()
	fun emitKBinaryExpression(node:KBinaryExpression):E=TODO()
	fun emitKAliasImport(node:KImportHeader.KAliasImport):E=TODO()
	fun emitKAnnotatedDelegationSpecifier(node:KAnnotatedDelegationSpecifier):E=TODO()
	fun emitKAnnotatedLambda(node:KAnnotatedLambda):E=TODO()
	fun emitKAnnotatedLambdaWithValueArguments(node:KAnnotatedLambdaWithValueArguments):E=TODO()
	fun emitKAnnotation(node:KAnnotation):E=TODO()
	fun emitKAnnotationKeyword(node:KAnnotationKeyword):E=TODO()
	fun emitKAnnotationLeft(node:KAnnotationLeft):E=TODO()
	fun emitKAnonymousFunction(node:KAnonymousFunction):E=TODO()
	fun emitKAnonymousInitializer(node:KAnonymousInitializer):E=TODO()
	fun emitKAsExpression(node:KAsExpression):E=TODO()
	fun emitKAssignableExpression(node:KAssignableExpression):E=when(node)
	{
		is KParenthesizedDirectlyAssignableExpression->emitKParenthesizedDirectlyAssignableExpression(node)
		is KPrefixUnaryExpression->emitKPrefixUnaryExpression(node)
	}

	fun emitKAssignableSuffix(node:KAssignableSuffix):E=TODO()
	fun emitKAssignableWithAndExpression(node:KAssignableWithAndExpression):E=TODO()
	fun emitKAssignment(node:KAssignment):E=TODO()
	fun emitKAssignmentLeft(node:KAssignmentLeft):E=when(node)
	{
		is KAssignableWithAndExpression->emitKAssignableWithAndExpression(node)
		is KParenthesizedDirectlyAssignableExpression->emitKParenthesizedDirectlyAssignableExpression(node)
		is KPostfixUnaryExpressionWithAssignableSuffix->emitKPostfixUnaryExpressionWithAssignableSuffix(node)
		is KSimpleIdentifier->emitKSimpleIdentifier(node)
	}

	fun emitKAt(node:KAt):E=TODO()

	fun emitKBinLiteral(node:KBinLiteral):E=TODO()
	fun emitKBlock(node:KBlock):E=TODO()
	fun emitKBreak(node:KBreak):E=TODO()
	fun emitKBreakAt(node:KBreakAt):E=TODO()
	fun emitKByKeyword(node:KByKeyword):E=TODO()

	fun emitKCallableReference(node:KCallableReference):E=TODO()
	fun emitKCallableReferenceInner(node:KCallableReferenceInner):E=TODO()
	fun emitKCallSuffix(node:KCallSuffix):E=TODO()
	fun emitKCallSuffixInner(node:KCallSuffixInner):E=when(node)
	{
		is KAnnotatedLambdaWithValueArguments->emitKAnnotatedLambdaWithValueArguments(node)
		is KValueArguments->emitKValueArguments(node)
	}

	fun emitKCatchBlock(node:KCatchBlock):E=TODO()
	fun emitKCatchesWithFinally(node:KCatchesWithFinally):E=TODO()
	fun emitKCatchKeyword(node:KCatchKeyword):E=TODO()
	fun emitKCharacterLiteral(node:KCharacterLiteral):E=TODO()
	fun emitKClassBody(node:KClassBody):E=TODO()
	fun emitKClassDeclaration(node:KClassDeclaration):E=TODO()
	fun emitKClassHeaderType(node:KClassHeaderType):E=when(node)
	{
		is KClassKeyword->emitKClassKeyword(node)
		is KFunInterfaceKeyword->emitKFunInterfaceKeyword(node)
		is KInterfaceKeyword->emitKInterfaceKeyword(node)
	}

	fun emitKClassKeyword(node:KClassKeyword):E=TODO()
	fun emitKClassMemberDeclaration(node:KClassMemberDeclaration):E=when(node)
	{
		is KAnonymousInitializer->emitKAnonymousInitializer(node)
		is KCompanionObject->emitKCompanionObject(node)
		is KClassDeclaration->emitKClassDeclaration(node)
		is KFunctionDeclaration->emitKFunctionDeclaration(node)
		is KObjectDeclaration->emitKObjectDeclaration(node)
		is KPropertyDeclaration->emitKPropertyDeclaration(node)
		is KTypeAlias->emitKTypeAlias(node)
		is KSecondaryConstructor->emitKSecondaryConstructor(node)
	}

	fun emitKClassOrEnumBody(node:KClassOrEnumBody):E=
		when(node)
		{
			is KClassBody->emitKClassBody(node)
			is KEnumClassBody->emitKEnumClassBody(node)
		}

	fun emitKClassParameter(node:KClassParameter):E=TODO()
	fun emitKCollectionLiteral(node:KCollectionLiteral):E=TODO()
	fun emitKCompanionKeyword(node:KCompanionKeyword):E=TODO()
	fun emitKCompanionObject(node:KCompanionObject):E=TODO()
	fun emitKComparison(node:KComparison):E=TODO()
	fun emitKConcreteTypeProjection(node:KConcreteTypeProjection):E=TODO()
	fun emitKConjunction(node:KConjunction):E=TODO()
	fun emitKConstKeyword(node:KConstKeyword):E=TODO()
	fun emitKConstModifier(node:KConstModifier):E=TODO()
	fun emitKConstructorDelegationCall(node:KConstructorDelegationCall):E=TODO()
	fun emitKConstructorInvocation(node:KConstructorInvocation):E=TODO()
	fun emitKConstructorKeyword(node:KConstructorKeyword):E=TODO()
	fun emitKContinue(node:KContinue):E=TODO()
	fun emitKContinueAt(node:KContinueAt):E=TODO()
	fun emitKControlStructureBody(node:KControlStructureBody):E=when(node)
	{
		is KBlock->emitKBlock(node)
		is KStatement->emitKStatement(node)
	}

	fun emitKControlStructureBodyOrSemicolon(node:KControlStructureBodyOrSemicolon):E=when(node)
	{
		is KBlock->emitKBlock(node)
		is KStatement->emitKStatement(node)
		is KSemicolon->emitKSemicolon(node)
	}

	fun emitKCrossinlineKeyword(node:KCrossinlineKeyword):E=TODO()

	fun emitKDataKeyword(node:KDataKeyword):E=TODO()
	fun emitKDeclaration(node:KDeclaration):E=when(node)
	{
		is KClassDeclaration->emitKClassDeclaration(node)
		is KFunctionDeclaration->emitKFunctionDeclaration(node)
		is KObjectDeclaration->emitKObjectDeclaration(node)
		is KPropertyDeclaration->emitKPropertyDeclaration(node)
		is KTypeAlias->emitKTypeAlias(node)
	}

	fun emitKDefinitelyNonNullableType(node:KDefinitelyNonNullableType):E=TODO()
	fun emitKDelegateKeyword(node:KDelegateKeyword):E=TODO()
	fun emitKDelegationSpecifier(node:KDelegationSpecifier):E=when(node)
	{
		is KConstructorInvocation->emitKConstructorInvocation(node)
		is KFunctionDelegationSpecifier->emitKFunctionDelegationSpecifier(node)
		is KUserType->emitKUserType(node)
	}

	fun emitKDelegationSpecifiers(node:KDelegationSpecifiers):E=TODO()
	fun emitKDirectlyAssignableExpression(node:KDirectlyAssignableExpression):E=when(node){
		is KParenthesizedDirectlyAssignableExpression->TODO()
		is KPostfixUnaryExpressionWithAssignableSuffix->TODO()
		is KSimpleIdentifier->emitKSimpleIdentifier(node)
	}
	fun emitKDisjunction(node:KDisjunction):E=TODO()
	fun emitKDoubleLiteral(node:KDoubleLiteral):E=TODO()
	fun emitKDoWhileStatement(node:KDoWhileStatement):E=TODO()
	fun emitKDynamicKeyword(node:KDynamicKeyword):E=TODO()

	fun emitKElvisExpression(node:KElvisExpression):E=TODO()
	fun emitKEnumClassBody(node:KEnumClassBody):E=TODO()
	fun emitKEnumEntries(node:KEnumEntries):E=TODO()
	fun emitKEnumEntry(node:KEnumEntry):E=TODO()
	fun emitKEnumKeyword(node:KEnumKeyword):E=TODO()
	fun emitKEquality(node:KEquality):E=TODO()
	fun emitKEscapedIdentifier(node:KEscapedIdentifier):E=TODO()
	fun emitKExcl(node:KExcl):E=TODO()
	fun emitKExpectKeyword(node:KExpectKeyword):E=TODO()
	fun emitKExpression(node:KExpression):E=when(node)
	{
		is KBinaryExpression->emitKBinaryExpression(node)
		is KAsExpression->emitKAsExpression(node)
		is KParenthesizedDirectlyAssignableExpression->emitKParenthesizedDirectlyAssignableExpression(node)
		is KPrefixUnaryExpression->emitKPrefixUnaryExpression(node)
		is KSimpleIdentifier->emitKSimpleIdentifier(node)
		is KComparison->emitKComparison(node)
		is KConjunction->emitKConjunction(node)
		is KPostfixUnaryExpressionWithAssignableSuffix->emitKPostfixUnaryExpressionWithAssignableSuffix(node)
		is KDisjunction->emitKDisjunction(node)
		is KEquality->emitKEquality(node)
		is KPostfixUnaryExpression->emitKPostfixUnaryExpression(node)
		is KCallableReference->emitKCallableReference(node)
		is KCollectionLiteral->emitKCollectionLiteral(node)
		is KAnonymousFunction->emitKAnonymousFunction(node)
		is KLambdaLiteral->emitKLambdaLiteral(node)
		is KIfExpression->emitKIfExpression(node)
		is KBreak->emitKBreak(node)
		is KBreakAt->emitKBreakAt(node)
		is KContinue->emitKContinue(node)
		is KContinueAt->emitKContinueAt(node)
		is KReturnExpression->emitKReturnExpression(node)
		is KThrowExpression->emitKThrowExpression(node)
		is EBooleanLiteral->emitEBooleanLiteral(node)
		is KBinLiteral->emitKBinLiteral(node)
		is KCharacterLiteral->emitKCharacterLiteral(node)
		is KHexLiteral->emitKHexLiteral(node)
		is KIntegerLiteral->emitKIntegerLiteral(node)
		is KLongLiteral->emitKLongLiteral(node)
		is KNullLiteral->emitKNullLiteral(node)
		is KDoubleLiteral->emitKDoubleLiteral(node)
		is KFloatLiteral->emitKFloatLiteral(node)
		is KUnsignedLiteral->emitKUnsignedLiteral(node)
		is KObjectLiteral->emitKObjectLiteral(node)
		is KParenthesizedExpression->emitKParenthesizedExpression(node)
		is KLineStringLiteral->emitKLineStringLiteral(node)
		is KMultiLineStringLiteral->emitKMultiLineStringLiteral(node)
		is KSuperAt->emitKSuperAt(node)
		is KTypeWithSimpleIdentifier->emitKTypeWithSimpleIdentifier(node)
		is KThis->emitKThis(node)
		is KThisAt->emitKThisAt(node)
		is KTryExpression->emitKTryExpression(node)
		is KWhenExpression->emitKWhenExpression(node)
		is KRangeExpression->emitKRangeExpression(node)
	}

	fun emitKExternalKeyword(node:KExternalKeyword):E=TODO()

	fun emitKFieldIdentifier(node:KFieldIdentifier):E=TODO()
	fun emitKFieldKeyword(node:KFieldKeyword):E=TODO()
	fun emitKFileAnnotation(node:KFileAnnotation):E=TODO()
	fun emitKFileKeyword(node:KFileKeyword):E=TODO()
	fun emitKFinalKeyword(node:KFinalKeyword):E=TODO()
	fun emitKFinallyBlock(node:KFinallyBlock):E=TODO()
	fun emitKFinallyKeyword(node:KFinallyKeyword):E=TODO()
	fun emitKFloatLiteral(node:KFloatLiteral):E=TODO()
	fun emitKForStatement(node:KForStatement):E=TODO()
	fun emitKFunctionAssignExpression(node:KFunctionAssignExpression):E=TODO()
	fun emitKFunctionBody(node:KFunctionBody):E=when(node)
	{
		is KBlock->emitKBlock(node)
		is KFunctionAssignExpression->emitKFunctionAssignExpression(node)
	}

	fun emitKFunctionDeclaration(node:KFunctionDeclaration):E=TODO()
	fun emitKFunctionDelegationSpecifier(node:KFunctionDelegationSpecifier):E=TODO()
	fun emitKFunctionLiteral(node:KFunctionLiteral):E=TODO()
	fun emitKFunctionType(node:KFunctionType):E=TODO()
	fun emitKFunctionTypeParameterInner(node:KFunctionTypeParameterInner):E=when(node)
	{
		is KParameter->emitKParameter(node)
		is KType->emitKType(node)
	}

	fun emitKFunctionValueParameter(node:KFunctionValueParameter):E=TODO()
	fun emitKFunctionValueParameterWithOptionalType(node:KFunctionValueParameterWithOptionalType):E=TODO()
	fun emitKFunInterfaceKeyword(node:KFunInterfaceKeyword):E=TODO()

	fun emitKGenericCallLikeComparison(node:KGenericCallLikeComparison):E=TODO()
	fun emitKGetKeyword(node:KGetKeyword):E=TODO()
	fun emitKGetter(node:KGetter):E=TODO()
	fun emitKGetterBody(node:KGetterBody):E=TODO()

	fun emitKHexLiteral(node:KHexLiteral):E=TODO()

	fun emitKIdentifier(node:KIdentifier):E=TODO()
	fun emitKIdentifierInner(node:KIdentifierInner):E=TODO()
	fun emitKIfExpression(node:KIfExpression):E=TODO()
	fun emitKIfInner(node:KIfInner):E=when(node)
	{
		is KBlock->emitKBlock(node)
		is KStatement->emitKStatement(node)
		is KIfInnerFull->emitKIfInnerFull(node)
		is KSemicolon->emitKSemicolon(node)
	}

	fun emitKIfInnerFull(node:KIfInnerFull):E=TODO()
	fun emitKImportHeader(node:KImportHeader):E=when(node)
	{
		is KImportHeader.KAliasImport->emitKAliasImport(node)
		is KImportHeader.KSingleImport->emitKSingleImport(node)
		is KImportHeader.KWildcardImport->emitKWildcardImport(node)
	}

	fun emitKImportKeyword(node:KImportKeyword):E=TODO()
	fun emitKIndexingSuffix(node:KIndexingSuffix):E=TODO()
	fun emitKInElvis(node:KInElvis):E=TODO()
	fun emitKInfixFunctionCall(node:KInfixFunctionCall):E=TODO()
	fun emitKInfixKeyword(node:KInfixKeyword):E=TODO()
	fun emitKInfixOperation(node:KInfixOperation):E=TODO()
	fun emitKInfixOperationInner(node:KInfixOperationInner):E=TODO()
	fun emitKInitKeyword(node:KInitKeyword):E=TODO()
	fun emitKInlineKeyword(node:KInlineKeyword):E=TODO()
	fun emitKInnerKeyword(node:KInnerKeyword):E=TODO()
	fun emitKIntegerHexBin(node:KIntegerHexBin):E=TODO()
	fun emitKIntegerLiteral(node:KIntegerLiteral):E=TODO()
	fun emitKInterfaceKeyword(node:KInterfaceKeyword):E=TODO()
	fun emitKInternalKeyword(node:KInternalKeyword):E=TODO()

	fun emitKJumpExpression(node:KJumpExpression):E=when(node)
	{
		is KBreak->emitKBreak(node)
		is KBreakAt->emitKBreakAt(node)
		is KContinue->emitKContinue(node)
		is KContinueAt->emitKContinueAt(node)
		is KReturnExpression->emitKReturnExpression(node)
		is KThrowExpression->emitKThrowExpression(node)
	}

	fun emitKKotlinFile(node:KKotlinFile):E=TODO()
	fun emitKKotlinScript(node:KKotlinScript):E=TODO()

	fun emitKLabel(node:KLabel):E=TODO()
	fun emitKLabelOrAnnotation(node:KLabelOrAnnotation):E=TODO()
	fun emitKLambdaLiteral(node:KLambdaLiteral):E=TODO()
	fun emitKLambdaParameter(node:KLambdaParameter):E=when(node)
	{
		is KMultiVariableDeclarationWithType->emitKMultiVariableDeclarationWithType(node)
		is KVariableDeclaration->emitKVariableDeclaration(node)
	}

	fun emitKLateinitKeyword(node:KLateinitKeyword):E=TODO()
	fun emitKLineStrEscapedChar(node:KLineStrEscapedChar):E=TODO()
	fun emitKLineStringContent(node:KLineStringContent):E=TODO()
	fun emitKLineStringContentOrExpression(node:KLineStringContentOrExpression):E=when(node)
	{
		is KEscapedIdentifier->emitKEscapedIdentifier(node)
		is KUniCharacterLiteral->emitKUniCharacterLiteral(node)
		is KLineStrRef->emitKLineStrRef(node)
		is KLineStrText->emitKLineStrText(node)
		is KLineStringExpression->emitKLineStringExpression(node)
	}

	fun emitKLineStringExpression(node:KLineStringExpression):E=TODO()
	fun emitKLineStringLiteral(node:KLineStringLiteral):E=TODO()
	fun emitKLineStrRef(node:KLineStrRef):E=TODO()
	fun emitKLineStrText(node:KLineStrText):E=TODO()
	fun emitKLiteralConstant(node:KLiteralConstant):E=TODO()
	fun emitKLongLiteral(node:KLongLiteral):E=TODO()
	fun emitKLoopStatement(node:KLoopStatement):E=TODO()

	fun emitKMemberAccessOperator(node:KMemberAccessOperator):E=TODO()
	fun emitKModifier(node:KModifier):E=TODO()
	fun emitKModifiersInner(node:KModifiersInner):E=when(node)
	{
		is KMultiAnnotation->emitKMultiAnnotation(node)
		is KSingleAnnotation->emitKSingleAnnotation(node)
		is EClassModifier->emitEClassModifier(node)
		is EFunctionModifier->emitEFunctionModifier(node)
		is EInheritanceModifier->emitEInheritanceModifier(node)
		is EMemberModifier->emitEMemberModifier(node)
		is EParameterModifier->emitEParameterModifier(node)
		is EVarianceModifier->emitEVarianceModifier(node)
		is EVisibilityModifier->emitEVisibilityModifier(node)
		is KActualKeyword->emitKActualKeyword(node)
		is KExpectKeyword->emitKExpectKeyword(node)
		is KConstModifier->emitKConstModifier(node)
	}

	fun emitKMultiAnnotation(node:KMultiAnnotation):E=TODO()
	fun emitKMultiLineStringContent(node:KMultiLineStringContent):E=TODO()
	fun emitKMultiLineStringExpression(node:KMultiLineStringExpression):E=TODO()
	fun emitKMultiLineStringLiteral(node:KMultiLineStringLiteral):E=TODO()
	fun emitKMultiLineStringLiteralInner(node:KMultiLineStringLiteralInner):E=TODO()
	fun emitKMultiLineStringQuote(node:KMultiLineStringQuote):E=TODO()
	fun emitKMultiLineStrRef(node:KMultiLineStrRef):E=TODO()
	fun emitKMultiLineStrText(node:KMultiLineStrText):E=TODO()
	fun emitKMultiOrSingleVariableDeclaration(node:KMultiOrSingleVariableDeclaration):E=when(node)
	{
		is KMultiVariableDeclaration->emitKMultiVariableDeclaration(node)
		is KVariableDeclaration->emitKVariableDeclaration(node)
	}

	fun emitKBinaryOperator(node:KBinaryOperator):E=TODO()
	fun emitKMultiVariableDeclaration(node:KMultiVariableDeclaration):E=TODO()
	fun emitKMultiVariableDeclarationWithType(node:KMultiVariableDeclarationWithType):E=TODO()

	fun emitKNavigationSuffix(node:KNavigationSuffix):E=TODO()
	fun emitKNavigationSuffixInner(node:KNavigationSuffixInner):E=when(node)
	{
		is KSimpleIdentifier->emitKSimpleIdentifier(node)
		is KClassKeyword->emitKClassKeyword(node)
		is KParenthesizedExpression->emitKParenthesizedExpression(node)
	}

	fun emitKNoinlineKeyword(node:KNoinlineKeyword):E=TODO()
	fun emitKNullableType(node:KNullableType):E=TODO()
	fun emitKNullLiteral(node:KNullLiteral):E=TODO()

	fun emitKObjectDeclaration(node:KObjectDeclaration):E=TODO()
	fun emitKObjectLiteral(node:KObjectLiteral):E=TODO()
	fun emitKOpenKeyword(node:KOpenKeyword):E=TODO()
	fun emitKOperatorKeyword(node:KOperatorKeyword):E=TODO()
	fun emitKOutKeyword(node:KOutKeyword):E=TODO()
	fun emitKOverrideKeyword(node:KOverrideKeyword):E=TODO()

	fun emitKPackageHeader(node:KPackageHeader):E=TODO()
	fun emitKParameter(node:KParameter):E=TODO()
	fun emitKParameterModifiers(node:KParameterModifiers):E=TODO()
	fun emitKParameterModifiersInner(node:KParameterModifiersInner):E=TODO()
	fun emitKParametersWithOptionalType(node:KParametersWithOptionalType):E=TODO()
	fun emitKParameterWithOptionalType(node:KParameterWithOptionalType):E=TODO()
	fun emitKParamKeyword(node:KParamKeyword):E=TODO()
	fun emitKParenthesizedDirectlyAssignableExpression(node:KParenthesizedDirectlyAssignableExpression):E=TODO()
	fun emitKParenthesizedExpression(node:KParenthesizedExpression):E=TODO()
	fun emitKParenthesizedOrFlatUserType(node:KParenthesizedOrFlatUserType):E=TODO()
	fun emitKParenthesizedType(node:KParenthesizedType):E=TODO()
	fun emitKParenthesizedUserType(node:KParenthesizedUserType):E=TODO()
	fun emitKPlatformModifier(node:KPlatformModifier):E=TODO()
	fun emitKPostfixUnaryExpression(node:KPostfixUnaryExpression):E=TODO()
	fun emitKPostfixUnaryExpressionWithAssignableSuffix(node:KPostfixUnaryExpressionWithAssignableSuffix):E=TODO()
	fun emitKPostfixUnaryOperator(node:KPostfixUnaryOperator):E=TODO()
	fun emitKPostfixUnarySuffix(node:KPostfixUnarySuffix):E=when(node)
	{
		is KCallSuffix->emitKCallSuffix(node)
		is KIndexingSuffix->emitKIndexingSuffix(node)
		is KNavigationSuffix->emitKNavigationSuffix(node)
		is KPostfixUnaryOperator->emitKPostfixUnaryOperator(node)
		is KTypeArguments->emitKTypeArguments(node)
	}

	fun emitKPrefixUnaryExpression(node:KPrefixUnaryExpression):E=TODO()
	fun emitKPrefixUnaryOperator(node:KPrefixUnaryOperator):E=TODO()
	fun emitKPrimaryConstructor(node:KPrimaryConstructor):E=TODO()
	fun emitKPrimaryExpression(node:KPrimaryExpression):E=when(node)
	{
		is KCallableReference->emitKCallableReference(node)
		is KCollectionLiteral->emitKCollectionLiteral(node)
		is KAnonymousFunction->emitKAnonymousFunction(node)
		is KLambdaLiteral->emitKLambdaLiteral(node)
		is KIfExpression->emitKIfExpression(node)
		is KBreak->emitKBreak(node)
		is KBreakAt->emitKBreakAt(node)
		is KContinue->emitKContinue(node)
		is KContinueAt->emitKContinueAt(node)
		is KReturnExpression->emitKReturnExpression(node)
		is KThrowExpression->emitKThrowExpression(node)
		is EBooleanLiteral->emitEBooleanLiteral(node)
		is KBinLiteral->emitKBinLiteral(node)
		is KCharacterLiteral->emitKCharacterLiteral(node)
		is KHexLiteral->emitKHexLiteral(node)
		is KIntegerLiteral->emitKIntegerLiteral(node)
		is KLongLiteral->emitKLongLiteral(node)
		is KNullLiteral->emitKNullLiteral(node)
		is KDoubleLiteral->emitKDoubleLiteral(node)
		is KFloatLiteral->emitKFloatLiteral(node)
		is KUnsignedLiteral->emitKUnsignedLiteral(node)
		is KObjectLiteral->emitKObjectLiteral(node)
		is KParenthesizedExpression->emitKParenthesizedExpression(node)
		is KAbstractKeyword->emitKAbstractKeyword(node)
		is KActualKeyword->emitKActualKeyword(node)
		is KAnnotationKeyword->emitKAnnotationKeyword(node)
		is KByKeyword->emitKByKeyword(node)
		is KCatchKeyword->emitKCatchKeyword(node)
		is KCompanionKeyword->emitKCompanionKeyword(node)
		is KConstKeyword->emitKConstKeyword(node)
		is KConstructorKeyword->emitKConstructorKeyword(node)
		is KCrossinlineKeyword->emitKCrossinlineKeyword(node)
		is KDataKeyword->emitKDataKeyword(node)
		is KDelegateKeyword->emitKDelegateKeyword(node)
		is KDynamicKeyword->emitKDynamicKeyword(node)
		is KEnumKeyword->emitKEnumKeyword(node)
		is KExpectKeyword->emitKExpectKeyword(node)
		is KExternalKeyword->emitKExternalKeyword(node)
		is KFieldKeyword->emitKFieldKeyword(node)
		is KFileKeyword->emitKFileKeyword(node)
		is KFinalKeyword->emitKFinalKeyword(node)
		is KFinallyKeyword->emitKFinallyKeyword(node)
		is KGetKeyword->emitKGetKeyword(node)
		is KIdentifierInner->emitKIdentifierInner(node)
		is KImportKeyword->emitKImportKeyword(node)
		is KInfixKeyword->emitKInfixKeyword(node)
		is KInitKeyword->emitKInitKeyword(node)
		is KInlineKeyword->emitKInlineKeyword(node)
		is KInnerKeyword->emitKInnerKeyword(node)
		is KInternalKeyword->emitKInternalKeyword(node)
		is KLateinitKeyword->emitKLateinitKeyword(node)
		is KNoinlineKeyword->emitKNoinlineKeyword(node)
		is KOpenKeyword->emitKOpenKeyword(node)
		is KOperatorKeyword->emitKOperatorKeyword(node)
		is KOutKeyword->emitKOutKeyword(node)
		is KOverrideKeyword->emitKOverrideKeyword(node)
		is KParamKeyword->emitKParamKeyword(node)
		is KPrivateKeyword->emitKPrivateKeyword(node)
		is KPropertyKeyword->emitKPropertyKeyword(node)
		is KProtectedKeyword->emitKProtectedKeyword(node)
		is KPublicKeyword->emitKPublicKeyword(node)
		is KReceiverKeyword->emitKReceiverKeyword(node)
		is KReifiedKeyword->emitKReifiedKeyword(node)
		is KSealedKeyword->emitKSealedKeyword(node)
		is KSetKeyword->emitKSetKeyword(node)
		is KSetparamKeyword->emitKSetparamKeyword(node)
		is KSuspendKeyword->emitKSuspendKeyword(node)
		is KTailrecKeyword->emitKTailrecKeyword(node)
		is KValueKeyword->emitKValueKeyword(node)
		is KVarargKeyword->emitKVarargKeyword(node)
		is KWhereKeyword->emitKWhereKeyword(node)
		is KLineStringLiteral->emitKLineStringLiteral(node)
		is KMultiLineStringLiteral->emitKMultiLineStringLiteral(node)
		is KSuperAt->emitKSuperAt(node)
		is KTypeWithSimpleIdentifier->emitKTypeWithSimpleIdentifier(node)
		is KThis->emitKThis(node)
		is KThisAt->emitKThisAt(node)
		is KTryExpression->emitKTryExpression(node)
		is KWhenExpression->emitKWhenExpression(node)
	}

	fun emitKPrivateKeyword(node:KPrivateKeyword):E=TODO()
	fun emitKPropertyDeclaration(node:KPropertyDeclaration):E=TODO()
	fun emitKPropertyKeyword(node:KPropertyKeyword):E=TODO()
	fun emitKPropertyModifier(node:KPropertyModifier):E=TODO()
	fun emitKProtectedKeyword(node:KProtectedKeyword):E=TODO()
	fun emitKPublicKeyword(node:KPublicKeyword):E=TODO()

	fun emitKRangeExpression(node:KRangeExpression):E=TODO()
	fun emitKRangeTest(node:KRangeTest):E=TODO()
	fun emitKRealLiteral(node:KRealLiteral):E=TODO()
	fun emitKReceiverKeyword(node:KReceiverKeyword):E=TODO()
	fun emitKReceiverType(node:KReceiverType):E=TODO()
	fun emitKRecieverTypeInner(node:KRecieverTypeInner):E=TODO()
	fun emitKReificationModifier(node:KReificationModifier):E=TODO()
	fun emitKReifiedKeyword(node:KReifiedKeyword):E=TODO()
	fun emitKReturnAt(node:KReturnAt):E=TODO()
	fun emitKReturnExpression(node:KReturnExpression):E=TODO()
	fun emitKReturnInner(node:KReturnInner):E=TODO()
	fun emitKReturnKeyword(node:KReturnKeyword):E=TODO()

	fun emitKSealedKeyword(node:KSealedKeyword):E=TODO()
	fun emitKSecondaryConstructor(node:KSecondaryConstructor):E=TODO()
	fun emitKSemicolon(node:KSemicolon):E=TODO()
	fun emitKSetKeyword(node:KSetKeyword):E=TODO()
	fun emitKSetparamKeyword(node:KSetparamKeyword):E=TODO()
	fun emitKSetter(node:KSetter):E=TODO()
	fun emitKSetterBody(node:KSetterBody):E=TODO()
	fun emitKSimpleIdentifier(node:KSimpleIdentifier):E=when(node)
	{
		is KAbstractKeyword->emitKAbstractKeyword(node)
		is KActualKeyword->emitKActualKeyword(node)
		is KAnnotationKeyword->emitKAnnotationKeyword(node)
		is KByKeyword->emitKByKeyword(node)
		is KCatchKeyword->emitKCatchKeyword(node)
		is KCompanionKeyword->emitKCompanionKeyword(node)
		is KConstKeyword->emitKConstKeyword(node)
		is KConstructorKeyword->emitKConstructorKeyword(node)
		is KCrossinlineKeyword->emitKCrossinlineKeyword(node)
		is KDataKeyword->emitKDataKeyword(node)
		is KDelegateKeyword->emitKDelegateKeyword(node)
		is KDynamicKeyword->emitKDynamicKeyword(node)
		is KEnumKeyword->emitKEnumKeyword(node)
		is KExpectKeyword->emitKExpectKeyword(node)
		is KExternalKeyword->emitKExternalKeyword(node)
		is KFieldKeyword->emitKFieldKeyword(node)
		is KFileKeyword->emitKFileKeyword(node)
		is KFinalKeyword->emitKFinalKeyword(node)
		is KFinallyKeyword->emitKFinallyKeyword(node)
		is KGetKeyword->emitKGetKeyword(node)
		is KIdentifierInner->emitKIdentifierInner(node)
		is KImportKeyword->emitKImportKeyword(node)
		is KInfixKeyword->emitKInfixKeyword(node)
		is KInitKeyword->emitKInitKeyword(node)
		is KInlineKeyword->emitKInlineKeyword(node)
		is KInnerKeyword->emitKInnerKeyword(node)
		is KInternalKeyword->emitKInternalKeyword(node)
		is KLateinitKeyword->emitKLateinitKeyword(node)
		is KNoinlineKeyword->emitKNoinlineKeyword(node)
		is KOpenKeyword->emitKOpenKeyword(node)
		is KOperatorKeyword->emitKOperatorKeyword(node)
		is KOutKeyword->emitKOutKeyword(node)
		is KOverrideKeyword->emitKOverrideKeyword(node)
		is KParamKeyword->emitKParamKeyword(node)
		is KPrivateKeyword->emitKPrivateKeyword(node)
		is KPropertyKeyword->emitKPropertyKeyword(node)
		is KProtectedKeyword->emitKProtectedKeyword(node)
		is KPublicKeyword->emitKPublicKeyword(node)
		is KReceiverKeyword->emitKReceiverKeyword(node)
		is KReifiedKeyword->emitKReifiedKeyword(node)
		is KSealedKeyword->emitKSealedKeyword(node)
		is KSetKeyword->emitKSetKeyword(node)
		is KSetparamKeyword->emitKSetparamKeyword(node)
		is KSuspendKeyword->emitKSuspendKeyword(node)
		is KTailrecKeyword->emitKTailrecKeyword(node)
		is KValueKeyword->emitKValueKeyword(node)
		is KVarargKeyword->emitKVarargKeyword(node)
		is KWhereKeyword->emitKWhereKeyword(node)
	}

	fun emitKSimpleUserType(node:KSimpleUserType):E=TODO()
	fun emitKSingleAnnotation(node:KSingleAnnotation):E=TODO()
	fun emitKSingleImport(node:KImportHeader.KSingleImport):E=TODO()
	fun emitKStarTypeProjection(node:KStarTypeProjection):E=TODO()
	fun emitKStatement(node:KStatement):E=TODO()
	fun emitKStatementInner(node:KStatementInner):E=when(node)
	{
		is KAssignment->emitKAssignment(node)
		is KAssignableWithAndExpression->emitKAssignableWithAndExpression(node)
		is KParenthesizedDirectlyAssignableExpression->emitKParenthesizedDirectlyAssignableExpression(node)
		is KPostfixUnaryExpressionWithAssignableSuffix->emitKPostfixUnaryExpressionWithAssignableSuffix(node)
		is KAbstractKeyword->emitKAbstractKeyword(node)
		is KActualKeyword->emitKActualKeyword(node)
		is KAnnotationKeyword->emitKAnnotationKeyword(node)
		is KByKeyword->emitKByKeyword(node)
		is KCatchKeyword->emitKCatchKeyword(node)
		is KCompanionKeyword->emitKCompanionKeyword(node)
		is KConstKeyword->emitKConstKeyword(node)
		is KConstructorKeyword->emitKConstructorKeyword(node)
		is KCrossinlineKeyword->emitKCrossinlineKeyword(node)
		is KDataKeyword->emitKDataKeyword(node)
		is KDelegateKeyword->emitKDelegateKeyword(node)
		is KDynamicKeyword->emitKDynamicKeyword(node)
		is KEnumKeyword->emitKEnumKeyword(node)
		is KExpectKeyword->emitKExpectKeyword(node)
		is KExternalKeyword->emitKExternalKeyword(node)
		is KFieldKeyword->emitKFieldKeyword(node)
		is KFileKeyword->emitKFileKeyword(node)
		is KFinalKeyword->emitKFinalKeyword(node)
		is KFinallyKeyword->emitKFinallyKeyword(node)
		is KGetKeyword->emitKGetKeyword(node)
		is KIdentifierInner->emitKIdentifierInner(node)
		is KImportKeyword->emitKImportKeyword(node)
		is KInfixKeyword->emitKInfixKeyword(node)
		is KInitKeyword->emitKInitKeyword(node)
		is KInlineKeyword->emitKInlineKeyword(node)
		is KInnerKeyword->emitKInnerKeyword(node)
		is KInternalKeyword->emitKInternalKeyword(node)
		is KLateinitKeyword->emitKLateinitKeyword(node)
		is KNoinlineKeyword->emitKNoinlineKeyword(node)
		is KOpenKeyword->emitKOpenKeyword(node)
		is KOperatorKeyword->emitKOperatorKeyword(node)
		is KOutKeyword->emitKOutKeyword(node)
		is KOverrideKeyword->emitKOverrideKeyword(node)
		is KParamKeyword->emitKParamKeyword(node)
		is KPrivateKeyword->emitKPrivateKeyword(node)
		is KPropertyKeyword->emitKPropertyKeyword(node)
		is KProtectedKeyword->emitKProtectedKeyword(node)
		is KPublicKeyword->emitKPublicKeyword(node)
		is KReceiverKeyword->emitKReceiverKeyword(node)
		is KReifiedKeyword->emitKReifiedKeyword(node)
		is KSealedKeyword->emitKSealedKeyword(node)
		is KSetKeyword->emitKSetKeyword(node)
		is KSetparamKeyword->emitKSetparamKeyword(node)
		is KSuspendKeyword->emitKSuspendKeyword(node)
		is KTailrecKeyword->emitKTailrecKeyword(node)
		is KValueKeyword->emitKValueKeyword(node)
		is KVarargKeyword->emitKVarargKeyword(node)
		is KWhereKeyword->emitKWhereKeyword(node)
		is KBlock->emitKBlock(node)
		is KClassDeclaration->emitKClassDeclaration(node)
		is KFunctionDeclaration->emitKFunctionDeclaration(node)
		is KObjectDeclaration->emitKObjectDeclaration(node)
		is KPropertyDeclaration->emitKPropertyDeclaration(node)
		is KTypeAlias->emitKTypeAlias(node)
		is KBinaryExpression->emitKBinaryExpression(node)
		is KAsExpression->emitKAsExpression(node)
		is KPrefixUnaryExpression->emitKPrefixUnaryExpression(node)
		is KComparison->emitKComparison(node)
		is KConjunction->emitKConjunction(node)
		is KDisjunction->emitKDisjunction(node)
		is KEquality->emitKEquality(node)
		is KPostfixUnaryExpression->emitKPostfixUnaryExpression(node)
		is KCallableReference->emitKCallableReference(node)
		is KCollectionLiteral->emitKCollectionLiteral(node)
		is KAnonymousFunction->emitKAnonymousFunction(node)
		is KLambdaLiteral->emitKLambdaLiteral(node)
		is KIfExpression->emitKIfExpression(node)
		is KBreak->emitKBreak(node)
		is KBreakAt->emitKBreakAt(node)
		is KContinue->emitKContinue(node)
		is KContinueAt->emitKContinueAt(node)
		is KReturnExpression->emitKReturnExpression(node)
		is KThrowExpression->emitKThrowExpression(node)
		is EBooleanLiteral->emitEBooleanLiteral(node)
		is KBinLiteral->emitKBinLiteral(node)
		is KCharacterLiteral->emitKCharacterLiteral(node)
		is KHexLiteral->emitKHexLiteral(node)
		is KIntegerLiteral->emitKIntegerLiteral(node)
		is KLongLiteral->emitKLongLiteral(node)
		is KNullLiteral->emitKNullLiteral(node)
		is KDoubleLiteral->emitKDoubleLiteral(node)
		is KFloatLiteral->emitKFloatLiteral(node)
		is KUnsignedLiteral->emitKUnsignedLiteral(node)
		is KObjectLiteral->emitKObjectLiteral(node)
		is KParenthesizedExpression->emitKParenthesizedExpression(node)
		is KLineStringLiteral->emitKLineStringLiteral(node)
		is KMultiLineStringLiteral->emitKMultiLineStringLiteral(node)
		is KSuperAt->emitKSuperAt(node)
		is KTypeWithSimpleIdentifier->emitKTypeWithSimpleIdentifier(node)
		is KThis->emitKThis(node)
		is KThisAt->emitKThisAt(node)
		is KTryExpression->emitKTryExpression(node)
		is KWhenExpression->emitKWhenExpression(node)
		is KRangeExpression->emitKRangeExpression(node)
		is KDoWhileStatement->emitKDoWhileStatement(node)
		is KForStatement->emitKForStatement(node)
		is KWhileStatement->emitKWhileStatement(node)
	}

	fun emitKStringLiteral(node:KStringLiteral):E=when(node)
	{
		is KLineStringLiteral->emitKLineStringLiteral(node)
		is KMultiLineStringLiteral->emitKMultiLineStringLiteral(node)
	}

	fun emitKSuperAt(node:KSuperAt):E=TODO()
	fun emitKSuperExpression(node:KSuperExpression):E=TODO()
	fun emitKSuspendKeyword(node:KSuspendKeyword):E=TODO()

	fun emitKTailrecKeyword(node:KTailrecKeyword):E=TODO()
	fun emitKThis(node:KThis):E=TODO()
	fun emitKThisAt(node:KThisAt):E=TODO()
	fun emitKThisExpression(node:KThisExpression):E=TODO()
	fun emitKThrowExpression(node:KThrowExpression):E=TODO()
	fun emitKTryExpression(node:KTryExpression):E=TODO()
	fun emitKTryExpressionInner(node:KTryExpressionInner):E=TODO()
	fun emitKType(node:KType):E=TODO()
	fun emitKTypeAlias(node:KTypeAlias):E=TODO()
	fun emitKTypeArguments(node:KTypeArguments):E=TODO()
	fun emitKTypeConstraint(node:KTypeConstraint):E=TODO()
	fun emitKTypeInner(node:KTypeInner):E=when(node)
	{
		is KDefinitelyNonNullableType->emitKDefinitelyNonNullableType(node)
		is KFunctionType->emitKFunctionType(node)
		is KParenthesizedType->emitKParenthesizedType(node)
		is KTypeReference.Dynamic->emitKTypeReference(node)
		is KUserType->emitKUserType(node)
	}

	fun emitKTypeModifier(node:KTypeModifier):E=TODO()
	fun emitKTypeParameter(node:KTypeParameter):E=TODO()
	fun emitKTypeParameterModifier(node:KTypeParameterModifier):E=TODO()
	fun emitKTypeParameterModifiers(node:KTypeParameterModifiers):E=TODO()
	fun emitKTypeProjection(node:KTypeProjection):E=when(node)
	{
		is KConcreteTypeProjection->emitKConcreteTypeProjection(node)
		is KStarTypeProjection->emitKStarTypeProjection(node)
	}

	fun emitKTypeProjectionModifier(node:KTypeProjectionModifier):E=TODO()
	fun emitKTypeReference(node:KTypeReference):E=TODO()
	fun emitKTypeTest(node:KTypeTest):E=TODO()
	fun emitKTypeWithSimpleIdentifier(node:KTypeWithSimpleIdentifier):E=TODO()

	fun emitKUnaryPrefix(node:KUnaryPrefix):E=TODO()
	fun emitKUnescapedAnnotation(node:KUnescapedAnnotation):E=TODO()
	fun emitKUniCharacterLiteral(node:KUniCharacterLiteral):E=TODO()
	fun emitKUnsignedLiteral(node:KUnsignedLiteral):E=TODO()
	fun emitKUserType(node:KUserType):E=TODO()

	fun emitKValueArgument(node:KValueArgument):E=TODO()
	fun emitKValueArguments(node:KValueArguments):E=TODO()
	fun emitKValueKeyword(node:KValueKeyword):E=TODO()
	fun emitKVarargKeyword(node:KVarargKeyword):E=TODO()
	fun emitKVariableDeclaration(node:KVariableDeclaration):E=TODO()
	fun emitKVariableDeclarationWithAnnotations(node:KVariableDeclarationWithAnnotations):E=TODO()

	fun emitKWhenCondition(node:KWhenCondition):E=TODO()
	fun emitKWhenElseEntry(node:KWhenElseEntry):E=TODO()
	fun emitKWhenEntry(node:KWhenEntry):E=TODO()
	fun emitKWhenEntryWithConditions(node:KWhenEntryWithConditions):E=TODO()
	fun emitKWhenExpression(node:KWhenExpression):E=TODO()
	fun emitKWhenSubject(node:KWhenSubject):E=TODO()
	fun emitKWhereKeyword(node:KWhereKeyword):E=TODO()
	fun emitKWhileStatement(node:KWhileStatement):E=TODO()
	fun emitKWildcardImport(node:KImportHeader.KWildcardImport):E=TODO()
}